In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.preprocessing import Imputer
from sklearn import decomposition
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from scipy import stats

from sklearn.datasets import load_iris

from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz

from sklearn import model_selection
from sklearn import metrics

# Problem 1

In [5]:
iris = load_iris()
X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = model_selection.train_test_split(X,
                                                                    y,
                                                                    test_size=0.2, 
                                                                    random_state=10)

for i in range(5):
    clf = DecisionTreeClassifier(max_depth=i+1, min_samples_split=5, min_samples_leaf=2, 
                                 min_impurity_split=0.095, random_state=6)
    clf = clf.fit(X_train,
                  y_train)
    expected = y_test
    predicted = clf.predict(X_test)
    print('max_depth =', i+1, '\n', metrics.classification_report(expected,
                                        predicted))
    
    with open("iris.dot",
          'w') as f:
        f = export_graphviz(clf,
                            out_file=f)
    import os
    os.system("dot -Tpdf iris.dot -o iris"+str(i+1)+".pdf")
    os.unlink('iris.dot')

max_depth = 1 
              precision    recall  f1-score   support

          0       1.00      1.00      1.00        10
          1       0.00      0.00      0.00        13
          2       0.35      1.00      0.52         7

avg / total       0.41      0.57      0.45        30

max_depth = 2 
              precision    recall  f1-score   support

          0       1.00      1.00      1.00        10
          1       1.00      0.85      0.92        13
          2       0.78      1.00      0.88         7

avg / total       0.95      0.93      0.93        30

max_depth = 3 
              precision    recall  f1-score   support

          0       1.00      1.00      1.00        10
          1       1.00      0.85      0.92        13
          2       0.78      1.00      0.88         7

avg / total       0.95      0.93      0.93        30

max_depth = 4 
              precision    recall  f1-score   support

          0       1.00      1.00      1.00        10
          1       1.00   

/Users/zioayr/anaconda3/lib/python3.5/site-packages/sklearn/tree/tree.py:282: DeprecationWarning: The min_impurity_split parameter is deprecated and will be removed in version 0.21. Use the min_impurity_decrease parameter instead.
  DeprecationWarning)
/Users/zioayr/anaconda3/lib/python3.5/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/Users/zioayr/anaconda3/lib/python3.5/site-packages/sklearn/tree/tree.py:282: DeprecationWarning: The min_impurity_split parameter is deprecated and will be removed in version 0.21. Use the min_impurity_decrease parameter instead.
  DeprecationWarning)
/Users/zioayr/anaconda3/lib/python3.5/site-packages/sklearn/tree/tree.py:282: DeprecationWarning: The min_impurity_split parameter is deprecated and will be removed in version 0.21. Use the min_impurity_decrease parameter instead.
  De

In [6]:
print(metrics.confusion_matrix(expected,
                               predicted))

[[10  0  0]
 [ 0 11  2]
 [ 0  0  7]]


In [7]:
with open("iris.dot",
          'w') as f:
    f = export_graphviz(clf,
                        out_file=f)
import os
os.system("dot -Tpdf iris.dot -o iris.pdf")
os.unlink('iris.dot')

# Problem 4

In [8]:
N = 1000
u1 = 5
u2 = -5
s = 2

x1 = np.random.normal(u1,s,N)
x2 = np.random.normal(u2,s,N)
c1 = np.repeat('c1',N)
c2 = np.repeat('c2',N)

df1 = pd.DataFrame(dict(zip(['feature','class'],[x1,c1])))
df2 = pd.DataFrame(dict(zip(['feature','class'],[x2,c2])))
df = pd.concat([df1, df2])

In [9]:
dfclf = DecisionTreeClassifier(max_depth=2)
dfclf = dfclf.fit(df.iloc[:,1].values.reshape(-1, 1), df.iloc[:,0].values.reshape(-1, 1))

In [10]:
with open("p4.dot",
          'w') as f:
        f = export_graphviz(dfclf,
                            out_file=f)
import os
os.system("dot -Tpdf p4.dot -o p4.pdf")
os.unlink('p4.dot')